#!/usr/bin/env python3
"""Embed brand-tokens.json and VERSION into index.html between the TOKENS markers.

    python3 scripts/embed-tokens.py          # update index.html
    python3 scripts/embed-tokens.py --check  # exit 1 if index.html is out of date (CI)

The page reads tokens from the embedded copy, so it works offline and from file://,
and CI guarantees it never disagrees with brand-tokens.json.
"""
import json, pathlib, re, sys

root = pathlib.Path(__file__).resolve().parent.parent
page = root / "index.html"
tokens = json.loads((root / "brand-tokens.json").read_text())
version = (root / "VERSION").read_text().strip()

block = (
    "<!-- TOKENS:BEGIN (generated by scripts/embed-tokens.py from brand-tokens.json and VERSION; do not edit by hand) -->\n"
    '<script type="application/json" id="brand-tokens">'
    + json.dumps(tokens, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    + "</script>\n"
    '<script type="application/json" id="brand-meta">'
    + json.dumps({"version": version})
    + "</script>\n<!-- TOKENS:END -->"
)
html = page.read_text()
new, n = re.subn(r"<!-- TOKENS:BEGIN.*?<!-- TOKENS:END -->", lambda _: block, html, flags=re.S)
if n != 1:
    sys.exit("index.html: TOKENS markers not found exactly once")
if "--check" in sys.argv:
    if new != html:
        sys.exit("index.html is out of date. Run: python3 scripts/embed-tokens.py")
    print("index.html tokens up to date")
else:
    page.write_text(new)
    print(f"embedded tokens (v{version}) into index.html")
